##
#
# THIS FILE IS AUTOGENERATED - EDIT THE PART FILES, NOT THIS FILE
#
##

##
#
# zprofile.d/00.zsh
#
##

# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

for f in /etc/zprofile.d/**/*.zsh(N); do; [ -r $f ] && source $f; done


##
#
# zprofile.d/macos-path-helper.zsh
#
##

##
# macOS path_helper utility
#
# The path_helper aims to simplify path management.
#
# The path_helper is located in /usr/libexec. 
#
# The path_helper reads the contents of the files in the 
# directories `/etc/paths.d` and `/etc/manpaths.d` and appends
# their contents to the PATH and MANPATH environment variables.
# Files in these directories contain one path element per line.
#
# See http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper
##

if [ -x /usr/libexec/path_helper ]; then
  eval `/usr/libexec/path_helper -s`
fi
